Enum user_role {
  student
  teacher
  superadmin
}

Table classes {
  id uuid [pk]
  class_name text
  class_code text
  teacher_id uuid
  deskripsi text
  created_at timestamptz
  updated_at timestamptz
  is_archived boolean
  announcement_enabled boolean
  announcement_title text
  announcement_content text
  announcement_tone text
  announcement_starts_at timestamptz
  announcement_ends_at timestamptz
  join_policy text
}

Table materials {
  id uuid [pk]
  class_id uuid
  uploader_id uuid
  judul text
  isi_materi text
  file_url text
  created_at timestamptz
  capaian_pembelajaran text
  kata_kunci text[]
  updated_at timestamptz
  display_order int4
}

Ref: materials.class_id > classes.id
