Enum user_role {
  student
  teacher
  superadmin
}

Table users {
  id uuid [pk]
  nama_lengkap text
  email text
  password text
  peran user_role
  nomor_identitas text
  username text
  created_at timestamptz
  foto_profil_url text
  mata_pelajaran text
  kelas_tingkat text
  institusi text
  bahasa text
  notif_email boolean
  notif_inapp boolean
  last_login_at timestamptz
  tanggal_lahir date
  mata_pelajaran_tambahan text
  pengalaman_mengajar int4
  tingkat_ajar text
  rombel_aktif text
  is_wali_kelas boolean
  no_whatsapp text
  bio_singkat text
  is_teacher_verified boolean
  ui_preferences jsonb
}

Table essay_submissions {
  id uuid [pk]
  soal_id uuid
  siswa_id uuid
  teks_jawaban text
  submitted_at timestamptz
  ai_grading_status text
  ai_graded_at timestamptz
  ai_grading_error text
  submission_type text
  attempt_count int4
}

Ref: essay_submissions.siswa_id > users.id
