Enum user_role {
  student
  teacher
  superadmin
}

Table materials {
  id uuid [pk]
  class_id uuid
  uploader_id uuid
  judul text
  isi_materi text
  file_url text
  created_at timestamptz
  capaian_pembelajaran text
  kata_kunci text[]
  updated_at timestamptz
  display_order int4
}

Table modules {
  id uuid [pk]
  material_id uuid
  nama_modul varchar
  file_url text
  created_at timestamptz
}

Ref: modules.material_id > materials.id
