Enum user_role {
  student
  teacher
  superadmin
}

Table classes {
  id uuid [pk]
  class_name text
  class_code text
  teacher_id uuid
  deskripsi text
  created_at timestamptz
  updated_at timestamptz
  is_archived boolean
  announcement_enabled boolean
  announcement_title text
  announcement_content text
  announcement_tone text
  announcement_starts_at timestamptz
  announcement_ends_at timestamptz
  join_policy text
}

Table class_members {
  id uuid [pk]
  class_id uuid
  user_id uuid
  joined_at timestamptz
  status varchar
  requested_at timestamptz
  approved_at timestamptz
}

Ref: class_members.class_id > classes.id
