export type SystemUpdateEntry = {
  version: string;
  date: string;
  title: string;
  majorUpdates: string[];
  minorUpdates: string[];
};

// Append-only changelog: tambahkan versi terbaru di paling atas, jangan hapus histori lama.
// Pisahkan poin dampak besar (major) dan penyempurnaan kecil/iteratif (minor).
export const SYSTEM_UPDATES: SystemUpdateEntry[] = [
  {
    version: "1.1",
    date: "2026-03-06",
    title: "Perbaikan UI Kelas/Soal + Stabilitas Dark Mode",
    majorUpdates: [
      "Menambahkan Mode Rubrik per card section pada halaman Teacher Soal (Per Soal vs Global), termasuk editor rubrik global, sinkronisasi rubrik ke soal, dan integrasi ke alur tambah/edit soal.",
      "Menambahkan guard transisi mode rubrik: konfirmasi eksplisit saat ganti mode, tooltip opsi mode, serta alert edukasi perbedaan Global vs Per Soal dengan rekomendasi akurasi AI.",
      "Menyempurnakan halaman Student Pengerjaan Soal: rubrik pada soal kini bisa collapse/buka, tata letak aksi coba ulang dipindah ke area aksi jawaban, dan mode daftar dibuat lebih compact dengan detail-on-demand per soal.",
      "Meng-upgrade Global Command Search (Ctrl/Cmd+K) agar pencarian Konten mencakup isi materi, teks soal, keyword, jawaban ideal, serta deskriptor rubrik untuk hasil yang lebih powerful.",
      "Merapikan struktur toolbar Section Workspace di halaman detail kelas teacher agar alur utama lebih fokus: heading workspace, primary action Tambah Section, search section, sort, filter, dan mode view.",
      "Menyederhanakan aksi per-section dengan tombol aksi langsung berbasis ikon (Tambah Konten, Edit, Hapus, Expand/Collapse), lengkap tooltip hover, warna aksi yang dibedakan, dan dukungan dark mode agar interaksi lebih cepat tanpa membuka menu overflow.",
      "Menyamakan pola aksi Table Mode dengan Card Mode melalui kontrol aksi langsung per-section agar interaksi lintas mode tetap konsisten.",
      "Merombak UI halaman Teacher Soal (route berbasis sectionCardId) agar lebih rapi dan fokus: tab bernuansa kapsul, kartu soal lebih terstruktur, serta kontrol aksi yang lebih cepat dipindai.",
      "Mendesain ulang modal Pengaturan Mode Pengerjaan Siswa dengan grouping berbasis kartu, segmented/capsule controls untuk opsi eksklusif, dan pemisahan section konfigurasi agar setup kuis lebih cepat.",
      "Menambahkan pengaturan baru `show_rubric_in_question` agar guru bisa menentukan rubrik ditampilkan atau disembunyikan saat siswa mengerjakan soal.",
      "Menambahkan pengurutan soal berbasis card section dengan tombol naik/turun serta drag-and-drop langsung pada daftar soal, lengkap persist urutan ke metadata `question_ids`.",
      "Merombak modal Buat/Edit Soal Essay menjadi fullscreen workflow, termasuk layout kontrol cepat + langkah form yang lebih terstruktur dan fokus input.",
      "Menambahkan mode input rubrik analitik yang bisa di-switch antara mode Kartu dan mode Tabel (mirip contoh tooltip), dengan sinkronisasi data rubrik yang tetap kompatibel saat disimpan.",
      "Menambahkan tooltip contoh rubrik Analitik/Holistik berbasis tabel agar guru lebih mudah memahami format penilaian.",
      "Menambahkan pengaturan integritas pengerjaan siswa untuk mode fullscreen + deteksi perpindahan tab, termasuk popup peringatan sebelum hard lock.",
      "Menambahkan opsi visibilitas hasil untuk siswa agar guru bisa menyembunyikan akses 'Hasil Penilaian / Lihat Hasil' sesuai kebutuhan sesi.",
      "Menambahkan mode submit semua jawaban sekaligus (bulk submit) pada pengerjaan siswa, sehingga semua jawaban dikirim sekali lewat tombol submit akhir.",
      "Menyempurnakan logika attempt/re-attempt agar mendukung limit tak terbatas (attempt=0), cooldown, dan pemilihan skor final best/last tanpa menyimpan semua nilai final berlebih.",
      "Menambahkan visibilitas jumlah attempt siswa pada area penilaian guru agar proses review percobaan lebih transparan.",
      "Menyempurnakan flow urut soal dengan affordance drag handle (`::`), kontrol naik/turun, border kontrol yang lebih rapi, serta animasi pergeseran saat reorder.",
    ],
    minorUpdates: [
      "Menambahkan badge indikator Rubrik Global pada daftar soal teacher saat mode global aktif agar scope penilaian langsung terlihat.",
      "Menambahkan hint interaksi buka/tutup pada panel rubrik siswa agar area soal panjang tetap mudah dipindai.",
      "Merapikan affordance dropdown detail per soal di mode daftar siswa (tap card untuk expand/collapse) agar tampilan awal tetap ringkas.",
      "Menambahkan ringkasan konteks workspace pada panel sticky untuk memperjelas fokus kerja (kelola urutan section, konten, dan aksi cepat).",
      "Merapikan posisi dan prioritas bulk action terpilih agar lebih terpisah dari kontrol filter utama.",
      "Menjaga kompatibilitas flow lama (table/card, tambah konten, edit/hapus section) sambil meningkatkan keterbacaan UI.",
      "Menambahkan empty state yang lebih jelas untuk hasil filter section kosong agar pengguna tahu langkah lanjutan yang tersedia.",
      "Menambahkan skeleton loading pada area daftar konten/soal per section saat data relasi soal masih dimuat.",
      "Menyelaraskan token warna tipe konten (materi/soal/tugas) lintas panel agar badge dan ikon tidak berbeda style antar-view.",
      "Menambahkan animasi transisi halus pada popup CRUD dan dropdown menu aksi section untuk feedback interaksi yang lebih natural.",
      "Menyederhanakan halaman detail kelas dengan menghapus panel ringkasan metrik atas yang duplikatif agar fokus langsung ke workspace dan aksi utama.",
      "Menstabilkan auto-refresh data setelah CRUD utama section/konten (tambah, edit, hapus) agar panel dan badge tidak perlu refresh manual.",
      "Menambahkan setting tampilan di workspace untuk show/hide label ordinal section (\"Section 1/2/...\"), termasuk persist preferensi per kelas.",
      "Menambahkan alur edit detail Materi Lengkap langsung dari modal edit konten melalui aksi \"edit di sini\" yang membuka popup editor rich text.",
      "Menghilangkan spinner panah atas/bawah pada seluruh input angka di modal pengaturan kuis agar tampilan lebih bersih dan konsisten.",
      "Mengembalikan border warna-warni per section pada modal pengaturan kuis (indigo/sky/emerald/violet/rose) sesuai preferensi visual terbaru.",
      "Menyempurnakan tampilan kartu daftar soal dengan badge nomor, chip metadata, panel detail yang lebih jelas, dan affordance kontrol urutan di sisi kiri.",
      "Menambahkan helper normalisasi deskriptor rubrik di halaman siswa untuk memastikan rendering rubrik stabil saat sumber data array maupun object.",
      "Mengoptimalkan performa render halaman Teacher Soal lewat memoisasi parsing section card, memo lookup soal by-id, dan normalisasi data list soal.",
      "Memecah komponen daftar soal menjadi sub-komponen terarah untuk memudahkan maintenance tanpa mengubah perilaku fitur.",
      "Menata ulang ukuran panel Rubrik agar lebih compact (rasio tipe rubrik diperkecil, font dan spacing dipadatkan) agar form lebih lega.",
      "Menambahkan tombol close pada alert error form soal (mis. teks soal kosong) agar pesan bisa ditutup manual.",
      "Menyesuaikan default tinggi textarea Teks Soal (rows 7) untuk mengurangi scroll berlebih saat input.",
      "Merapikan kontrol di modal soal: tombol hide/show yang tidak diperlukan dihapus, posisi aksi disusun ulang, dan tab langkah dipadatkan.",
      "Menyelaraskan dark mode lintas role untuk topbar, sidebar, panel, card, badge, label, input, popover, dan command palette agar kontras lebih konsisten.",
      "Menambahkan override dark mode scoped untuk halaman berat (teacher material, teacher class detail, teacher penilaian, student class detail, student material detail) guna menutup kebocoran warna utilitas.",
      "Menonaktifkan gradient panel/card pada dark mode (fallback ke solid dark surface) agar tidak muncul layer abu terang yang mengganggu.",
      "Memperbaiki kontras elemen aktif sidebar di dark mode (termasuk indikator active dan badge info) agar state aktif lebih jelas terbaca.",
      "Memperbaiki kontras link navigasi 'Kembali ke Detail Kelas' / 'Kembali ke Daftar Kelas' di dark mode.",
      "Memperbaiki kontras badge angka pada Workspace Sidebar (Ruang Kelas) agar nilai badge tetap terlihat pada state aktif/nonaktif.",
      "Merapikan mapping tipe callback edit soal (`QuestionItem` -> `EssayQuestion`) untuk menghilangkan error TypeScript mismatch dan menstabilkan build check.",
    ],
  },
  {
    version: "1.0",
    date: "2026-03-05",
    title: "Publish Pertama",
    majorUpdates: [
      "Menambahkan mode Spreadsheet di Manajemen User (Superadmin) agar edit data user lebih cepat, termasuk perbaikan struktur kolom berdasarkan role (guru/siswa) dan optimasi lebar kolom.",
      "Menambahkan fitur Ajukan Banding Nilai (Student), termasuk status banding, alasan banding, dan tampilan riwayat banding pada area nilai/feedback.",
      "Menyempurnakan modul review banding nilai di sisi Teacher (proses, terima, tolak) dengan state aksi yang lebih jelas dan feedback UI yang lebih informatif.",
      "Memperbaiki endpoint dan alur API banding nilai agar halaman teacher penilaian tidak lagi gagal memuat data banding karena mismatch route.",
      "Memperbaiki query backend banding nilai (error PostgreSQL uuid=text) agar listing banding untuk student/teacher berjalan stabil.",
      "Menyempurnakan tampilan Student Grades agar lebih actionable: ringkasan KPI, prioritas tindakan, detail per konten/per soal, dan konteks feedback terbaru.",
      "Menambahkan status proses AI grading (queued/processing/waiting_result/failed) pada alur jawaban essay beserta indikator loading/polling hasil.",
      "Menambahkan kontrol feature flag `feature_show_updates_sidebar` di panel Superadmin Feature Flags untuk show/hide menu Update Sistem/Revisi.",
      "Menambahkan halaman baru 'Update Sistem/Revisi' yang bisa diakses dari semua role (Student, Teacher, Superadmin).",
      "Menambahkan Global Command Search di Topbar (Ctrl/Cmd+K) dengan hasil terkelompok (Terakhir, Aksi, Navigasi, Kelas, Siswa, Konten), keyboard navigation, quick action, dan recent commands per-user.",
      "Merapikan dark mode halaman Teacher Penilaian pada panel utama (header, kartu ringkasan, daftar kelas/siswa, input kontrol) agar kontras konsisten antara mode terang dan gelap.",
      "Memperbaiki alur tab pada route Teacher Soal berbasis sectionCardId agar tab 'Submisi Siswa' bisa dipilih normal (tidak lagi dipaksa kembali ke tab daftar soal).",
      "Menyempurnakan modal Tambah Soal untuk mobile: layout responsif, panel parameter bisa ditampilkan/disembunyikan, tombol aksi dipadatkan, dan area kontrol cepat bisa di-collapse.",
    ],
    minorUpdates: [
      "Menghubungkan sidebar semua role ke public feature flag agar visibilitas menu update bisa dikendalikan terpusat dari Superadmin.",
      "Finalisasi dark mode sidebar (teks, border, hover, submenu, settings, dan panel profil mobile) agar kontras konsisten.",
      "Menambahkan navigasi keyboard di mode spreadsheet serta penyempurnaan interaksi edit cepat agar workflow administrasi lebih efisien.",
      "Memperbaiki struktur tampilan rubrik agar rubrik ditampilkan per soal (bukan duplikat agregat di luar soal), sehingga interpretasi penilaian lebih akurat.",
      "Menyempurnakan UX submit jawaban/tugas dengan pesan status yang lebih jelas untuk mode instant maupun queued.",
      "Perbaikan besar dark mode di berbagai halaman student (terutama kelas, badges, status, cards, feedback blocks) agar kontras lebih konsisten.",
      "Perbaikan navigasi mobile: topbar disederhanakan, floating tombol sidebar disesuaikan, serta alur profil/logout mobile dibuat lebih rapi.",
      "Peningkatan stabilitas deploy container/frontend-backend-env untuk environment server agar proxy API dan komunikasi antar service lebih konsisten.",
      "Menambahkan menu sidebar khusus dengan style berbeda untuk menonjolkan info pengembangan sistem.",
      "Menyesuaikan wording CTA di halaman detail kelas teacher dari 'Tambah Konten' menjadi 'Tambah Section' pada area global agar hierarki aksi lebih jelas.",
      "Menghapus opsi tipe konten 'Penilaian' dari dropdown Tambah Konten di section karena tidak lagi dipakai pada alur konten aktif.",
      "Memperbaiki endpoint/update mode grading agar toggle Instant/Queued stabil, termasuk fallback ke endpoint setting generik dan perbaikan prioritas route spesifik di backend.",
      "Meningkatkan visibilitas pesan error update mode grading di UI agar sumber kegagalan lebih mudah ditelusuri.",
      "Merapikan interaksi mobile pada form langkah (Soal/Rubrik/Preview) agar tidak menutupi konten penting saat proses input panjang.",
    ],
  },
];
